server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/waterbillingdb
spring.data.mongodb.auto-index-creation=true

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Razorpay Configuration
razorpay.key.id=rzp_test_TO7prfOwJ2tD8k
razorpay.key.secret=BnL3tZEbbVe4WDJDcw0YvF2u
